# Generated by Django 4.0.5 on 2022-07-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_Producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='pordesct',
            field=models.IntegerField(verbose_name='porcentaje de descuento'),
        ),
    ]
