# Generated by Django 4.0.6 on 2022-07-09 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_Producto', '0002_alter_promocion_pordesct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False, verbose_name='id categoria')),
                ('nombreCategoria', models.CharField(max_length=255, verbose_name='nombre categoria')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rest_Producto.categoria', verbose_name='Categoria de producto'),
            preserve_default=False,
        ),
    ]
