# Generated by Django 4.0.5 on 2022-07-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_Producto', '0003_categoria_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=1500, verbose_name='Descripcion de producto'),
        ),
    ]
