# Generated by Django 4.0.6 on 2022-07-10 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_Producto', '0004_alter_producto_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocion',
            name='producto',
        ),
        migrations.CreateModel(
            name='PromocionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_Producto.producto')),
                ('idPromocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_Producto.promocion')),
            ],
        ),
    ]
