# Generated by Django 4.0.5 on 2022-07-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_Producto', '0005_remove_promocion_producto_promocionproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='descripcion',
            field=models.CharField(max_length=512, null=True, verbose_name='descripcion de promoción'),
        ),
    ]
