# Generated by Django 4.0.6 on 2022-07-10 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_Producto', '0007_alter_promocionproducto_idpromocion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocionproducto',
            name='idProducto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_Producto.producto'),
        ),
    ]
