# Generated by Django 4.0.6 on 2022-07-10 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_Producto', '0008_alter_promocionproducto_idproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocionproducto',
            name='idProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_Producto.producto'),
        ),
        migrations.AlterField(
            model_name='promocionproducto',
            name='idPromocion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_Producto.promocion'),
        ),
    ]
