# Generated by Django 4.0.5 on 2022-07-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Usuario')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de Usuario')),
                ('apellidos', models.CharField(max_length=255, verbose_name='Apellidos de Usuario')),
                ('correo', models.CharField(max_length=255, verbose_name='Correo de Usuario')),
                ('direccion', models.CharField(max_length=255, verbose_name='Direccion de Usuario')),
                ('telefono', models.CharField(max_length=255, verbose_name='Telefono de Usuario')),
                ('comuna', models.CharField(max_length=255, verbose_name='Comuna de Usuario')),
                ('region', models.CharField(max_length=255, verbose_name='Region de Usuario')),
                ('rut', models.CharField(max_length=255, verbose_name='Rut de Usuario')),
                ('isSuscrito', models.BooleanField(default=False, verbose_name='Isuscrito de Usuario')),
                ('fechaSuscrito', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Suscrito de Usuario')),
                ('isAdmin', models.BooleanField(default=False, verbose_name='Isadmin de Usuario')),
            ],
        ),
    ]
