# Generated by Django 4.0.5 on 2022-07-09 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='prueba',
            field=models.CharField(max_length=50, null=True, verbose_name='Prueba de Usuario'),
        ),
    ]
