# Generated by Django 4.0.5 on 2022-07-09 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_Usuario', '0002_usuario_prueba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='prueba',
        ),
    ]
