# Generated by Django 4.0.5 on 2022-07-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_Usuario', '0003_remove_usuario_prueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='provincia',
            field=models.CharField(max_length=255, null=True, verbose_name='Provincia de Usuario'),
        ),
    ]
